[package]
name = "matrix"
version = "0.1.0"
authors = ["tree <treed018@odu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# num-traits = "*"
